name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build TypeScript
        run: npx --package typescript tsc

      - name: Configure NPM Credentials
        run: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: NPM Pre-Publish Checks
        run: |
          node -p "'IS_PUBLISHED=' + $(npm view @lazy/oauth2-implicit-grant-client versions --json 2>/dev/null || echo "[]").includes(require('./package.json').version)" >> $GITHUB_ENV

      - name: NPM Publish
        if: ${{ env.IS_PUBLISHED == 'false' }}
        run: npm publish --access=public
